// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BannersController from "./banners_controller"
application.register("banners", BannersController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PokemonStatsController from "./pokemon_stats_controller"
application.register("pokemon-stats", PokemonStatsController)
